/// @description Variables
lanes = [];
hueButtons = [];
speedButtons = [];
keyButtons = [];
array_push(lanes, instance_find(objEditorLane, 0));
array_push(hueButtons, instance_find(objLaneHue, 0));
array_push(speedButtons, instance_find(objLaneSpeed, 0));
array_push(keyButtons, instance_find(objLaneKey, 0));
numLanes = 1;
maxLanes = 7;